name: Deploy Auth Service

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: jodegen
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/jodegen/auth-service:latest
          build-args: |
            GITHUB_TOKEN=${{ secrets.GHCR_TOKEN }}

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u jodegen --password-stdin

            docker pull ghcr.io/jodegen/auth-service:latest

            docker stop auth-service || true
            docker rm auth-service || true

            docker run -d \
              --name auth-service \
              --network microservices-net \
              -p 6772:6772 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e EUREKA_URL=${{ secrets.EUREKA_URL }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e DB_HOST=${{ secrets.DB_HOST }} \
              -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -v /opt/microservices/auth-service:/app/data \
              ghcr.io/jodegen/auth-service:latest